<?php include 'header.php'; ?>
<script>
$( function() {
	$('#prev').button({
	  icon: "ui-icon-triangle-1-w"
	}).click(function() {
		localStorage.setItem("memory", $('input:checked').val());
		if(localStorage.getItem("board")=="ra_star")
		{
			window.location.href = "wizard_cloudpassword.php";
		}
		else
		{
			window.location.href = "wizard_board.php";
		}
	});
	$('#next').button({
	  icon: "ui-icon-triangle-1-e",
	  iconPosition: "end"
	}).click(function() {
		localStorage.setItem("memory", $('input:checked').val());
		window.location.href = "wizard_temperature.php";
	});
	$( "input[name=memsettings]" ).checkboxradio();
	if(localStorage.getItem("memory")!="")
	{
		$("input[name=memsettings][value=" + localStorage.getItem("memory") + "]").prop('checked', true);
		$("input[name=memsettings]").checkboxradio( "refresh" );
	}
});
</script>

<div id="sidemenu" class="split split-horizontal">
<div id=logo></div>
<a href="/webwizard"><img src="image/left_arrow.png" align="absmiddle"> Back to Code View</a>
<button id=go_board class="ui-button ui-widget ui-corner-all go_buttons">Board</button>
<button id=go_memory class="ui-button ui-widget ui-corner-all go_buttons">Memory</button>
<button id=go_temperature class="ui-button ui-widget ui-corner-all go_buttons">Temperature</button>
<button id=go_expansion class="ui-button ui-widget ui-corner-all go_buttons">Expansion</button>
<button id=go_attachment class="ui-button ui-widget ui-corner-all go_buttons">Attachments</button>
<button id=go_mainrelay class="ui-button ui-widget ui-corner-all go_buttons">Main Relay</button>
<button id=go_relayexpansion class="ui-button ui-widget ui-corner-all go_buttons">Relay Expansion 1</button>
<button id=go_relayexpansion2 class="ui-button ui-widget ui-corner-all go_buttons">Relay Expansion 2</button>
<button id=go_standarddimming class="ui-button ui-widget ui-corner-all go_buttons">Standard Dimming</button>
<button id=go_dimmingexpansion class="ui-button ui-widget ui-corner-all go_buttons">Dimming Expansion</button>
<button id=go_rfexpansion class="ui-button ui-widget ui-corner-all go_buttons">RF Expansion</button>
<button id=go_dcpumpattachment class="ui-button ui-widget ui-corner-all go_buttons">DC Pump</button>
<button id=go_buzzer class="ui-button ui-widget ui-corner-all go_buttons">Buzzer</button>
<button id=go_ifthen class="ui-button ui-widget ui-corner-all go_buttons">If / Then</button>

<button id=go_ready class="ui-button ui-widget ui-corner-all go_buttons">Generate</button>

</div>
<div id="main" class="split split-horizontal">
    <h1>Reef Angel Web Wizard</h1>
    <h2>Memory Settings</h2>
	<p>User settings can be stored within the code itself or inside the intenal memory of the controller.<br>Example of these settings are light schedule, heater/chiller temperature and many other settings.<br>Settings stored within the code itself is the easiest way to program your controller because it will not require you to use any other application. This is the recommended method for new users.<br>The code generated by the Reef Angel Wizard will contain all the information needed and the controller will be ready to be used.<br>Settings that are stored inside the intenal memory will require you to use another application after you upload the code generated by the Reef Angel Wizard.<br>The benefit of using another application is that you will be able to change it at any time without having to generate a new code.<br>One good example is changing your light schedule using one of the smart phone apps.<br><br>Where would you like to store your settings?</p>
    <label for="code">In the code (Recommended for new users)</label>
    <input type="radio" id="code" name="memsettings" value="code" checked>
    <br>
    <label for="internal">In the internal memory</label>
    <input type="radio" id="internal" name="memsettings" value="internal">
    <div id=footer>
    <button id=prev class="ui-button ui-widget ui-corner-all">Prev</button>
    <button id=next class="ui-button ui-widget ui-corner-all">Next</button>
    </div>
</div>




<?php include 'footer.php'; ?>